
export const navConfig = (t) => [



  {
    moduleName: "hr",
    label: "nav.hr",
    icon: "Users",
    resource: "Employee",
    action: "canRead",
    path: "/hr",
    children: [
      {
        moduleName: "hr",
        label: "nav.employees",
        icon: "Users",
        path: "/hr/employees/list",
        resource: "Employee",
        action: "canRead",
        children: [
          {
            moduleName: "hr",
            label: "nav.employeeList",
            icon: "UserCheck",
            path: "/hr/employees/list",
            resource: "Employee",
            action: "canRead",
          },
        ],
      },
      {
        moduleName: "hr",
        label: "nav.recruitment",
        icon: "Briefcase",
        path: "/hr/recruitment",
        resource: "StaffingPlan",
        action: "canRead",
        children: [
          {
            moduleName: "hr",
            label: "nav.staffingPlans",
            icon: "ClipboardList",
            path: "/hr/recruitment/staffing-plans",
            resource: "StaffingPlan",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.jobRequisitions",
            icon: "FileText",
            path: "/hr/recruitment/job-requisitions",
            resource: "JobRequisition",
            action: "canRead",
          },
        ],
      },
      {
        moduleName: "hr",
        label: "nav.roles",
        icon: "Shield",
        path: "/hr/roles",
        resource: "Role",
        action: "canRead",
        children: [
          {
            moduleName: "hr",
            label: "nav.roleList",
            icon: "List",
            path: "/hr/roles/list",
            resource: "Role",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.rolePermissions",
            icon: "ShieldCheck",
            path: "/hr/roles/permissions",
            resource: "RolePermission",
            action: "canRead",
          },

          {
            moduleName: "hr",
            label: "nav.roleProfiles",
            icon: "UserCog",
            path: "/hr/roles/profiles",
            resource: "RoleProfile",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.userRoles",
            icon: "Users",
            path: "/hr/roles/user-roles",
            resource: "UserRole",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.userPermissions",
            icon: "Key",
            path: "/hr/roles/user-permissions",
            resource: "UserPermission",
            action: "canRead",
          },
        ],
      },
      {
        moduleName: "hr",
        label: "nav.organization",
        icon: "Building2",
        path: "/hr/organization",
        resource: "Company",
        action: "canRead",
        children: [
          {
            moduleName: "hr",
            label: "nav.companies",
            icon: "Building",
            path: "/hr/organization/companies",
            resource: "Company",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.branches",
            icon: "GitBranch",
            path: "/hr/organization/branches",
            resource: "Branch",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.departments",
            icon: "Layers",
            path: "/hr/organization/departments",
            resource: "Department",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.designations",
            icon: "Tag",
            path: "/hr/organization/designations",
            resource: "Designation",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.employmentTypes",
            icon: "Briefcase",
            path: "/hr/organization/employment-types",
            resource: "EmploymentType",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.employeeGrades",
            icon: "GraduationCap",
            path: "/hr/organization/employee-grades",
            resource: "EmployeeGrade",
            action: "canRead",
          },
        ],
      },
      {
        moduleName: "hr",
        label: "nav.documents",
        icon: "FileText",
        path: "/hr/documents",
        resource: "Document",
        action: "canRead",
        children: [
          {
            moduleName: "hr",
            label: "nav.documentTypes",
            icon: "FolderOpen",
            path: "/hr/documents/types",
            resource: "DocumentType",
            action: "canRead",
          },
            {
            moduleName: "hr",
            label: "Document Managment",
            icon: "FolderOpen",
            path: "/hr/documents/managmenet",
            resource: "Document",
            action: "canRead",
          },
          {
            moduleName: "hr",
            label: "nav.compliance",
            icon: "ShieldAlert",
            path: "/hr/documents/compliance",
            resource: "Document",
            action: "canRead",
          },
        ],
      },
      {
        moduleName: "hr",
        label: "nav.leave",
        icon: "Calendar",
        path: "/hr/leave",
        resource: "LeaveApplication",
        action: "canRead",
        children: [
          {
            label: "Leave Dashboard",
            path: "/hr/leave/dashboard",
            resource: "LeaveDashboard",
            action: "canRead",
          },
          {
            label: "Leave Applications",
            path: "/hr/leave/applications",
            resource: "LeaveApplication",
            action: "canRead",
          },
          {
            label: "Ledger",
            path: "/hr/leave/ledger",
            resource: "LeaveLedgerEntry",
            action: "canRead",
          },

          {
            label: "Operational",
            path: "/hr/leave/config",
            resource: "LeaveType",
            action: "canRead",
            children: [
              {
                label: "Holiday Lists",
                path: "/hr/leave/holidays",
                resource: "HolidayList",
                action: "canRead",
              },
              {
                label: "Block Lists",
                path: "/hr/leave/block-lists",
                resource: "LeaveBlockList",
                action: "canRead",
              },
              {
                label: "Compensatory Leave",
                path: "/hr/leave/compensatory",
                resource: "CompensatoryLeaveRequest",
                action: "canRead",
              },
              {
                label: "Encashments",
                path: "/hr/leave/encashments",
                resource: "LeaveEncashment",
                action: "canRead",
              },
            ],
          },

          {
            label: "Configurations",
            path: "/hr/leave/config",
            resource: "LeaveType",
            action: "canRead",
            children: [
              {
                label: "Leave Types",
                path: "/hr/leave/types",
                resource: "LeaveType",
                action: "canRead",
              },
              {
                label: "Leave Periods",
                path: "/hr/leave/periods",
                resource: "LeavePeriod",
                action: "canRead",
              },
            ],
          },
        ],
      },
    ],
  },
    // ═══════════════ SELF-SERVICE (My Profile) ═══════════════
{
  moduleName: "self-service",
  label: "HR Profile",
  icon: "User",
  resource: "Employee",
  action: "canReadSelf",
  path: "/my/profile",  // ← parent path (not navigable)
  children: [
    {
      moduleName: "self-service",
      label: "My Leave",
      icon: "Calendar",
      path: "/my/profile/leave",
      resource: "LeaveApplication",
      action: "canReadSelf",
    },
    {
      moduleName: "self-service",
      label: "My Ledger",
      icon: "Calendar",
      path: "/my/profile/ledger",
      resource: "LeaveApplication",
      action: "canReadSelf",
    },
    {
      moduleName: "self-service",
      label: "My Documents",
      icon: "FileText",
      path: "/my/profile/documents",
      resource: "Document",
      action: "canReadSelf",
    },
    {
      moduleName: "self-service",
      label: "My Details",
      icon: "User",
      path: "/my/profile/details",
      resource: "Employee",
      action: "canReadSelf",
    },
  ],
},
  {
    moduleName: "finance",
    label: "nav.finance",
    icon: "Wallet",
    resource: "Invoice",
    action: "canRead",
    path: "/finance",
    children: [
      {
        moduleName: "finance",
        label: "nav.invoices",
        icon: "Receipt",
        path: "/finance/invoices",
        resource: "Invoice",
        action: "canRead",
      },
      {
        moduleName: "finance",
        label: "nav.payments",
        icon: "CreditCard",
        path: "/finance/payments",
        resource: "Payment",
        action: "canRead",
      },
      {
        moduleName: "finance",
        label: "nav.reports",
        icon: "BarChart3",
        path: "/finance/reports",
        resource: "FinancialReport",
        action: "canReport",
      },
    ],
  },
  {
    moduleName: "sales",
    label: "nav.sales",
    icon: "ShoppingCart",
    resource: "SalesOrder",
    action: "canRead",
    path: "/sales",
    children: [
      {
        moduleName: "sales",
        label: "nav.orders",
        icon: "ShoppingBag",
        path: "/sales/orders",
        resource: "SalesOrder",
        action: "canRead",
      },
      {
        moduleName: "sales",
        label: "nav.customers",
        icon: "Users",
        path: "/sales/customers",
        resource: "Customer",
        action: "canRead",
      },
      {
        moduleName: "sales",
        label: "nav.agents",
        icon: "UserCog",
        path: "/sales/agents",
        resource: "SalesAgent",
        action: "canRead",
      },
    ],
  },
  {
    moduleName: "projects",
    label: "nav.projects",
    icon: "FolderKanban",
    resource: "Project",
    action: "canRead",
    path: "/projects",
    children: [
      {
        moduleName: "projects",
        label: "nav.allProjects",
        icon: "FolderKanban",
        path: "/projects",
        resource: "Project",
        action: "canRead",
      },
      {
        moduleName: "projects",
        label: "nav.myTasks",
        icon: "CheckSquare",
        path: "/projects/tasks",
        resource: "Task",
        action: "canRead",
      },
      {
        moduleName: "projects",
        label: "nav.milestones",
        icon: "Flag",
        path: "/projects/milestones",
        resource: "Milestone",
        action: "canRead",
      },
    ],
  },
];
